language: node_js

dist: trusty

addons:
  chrome: stable

node_js:
  - '10'

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm test
  - npm run build
